CREATE TABLE IF NOT EXISTS weather (
    station_id VARCHAR(14) NOT NULL,
    date DATE NOT NULL,
    n_records INTEGER,
    air_temperature_avg DECIMAL(15, 5),
    air_temperature_min DECIMAL(15, 5),
    air_temperature_max DECIMAL(15, 5),
    dew_point_avg DECIMAL(15, 5),
    dew_point_min DECIMAL(15, 5),
    dew_point_max DECIMAL(15, 5),
    sea_lvl_pressure_avg DECIMAL(15, 5),
    sea_lvl_pressure_min DECIMAL(15, 5),
    sea_lvl_pressure_max DECIMAL(15, 5),
    wind_direction DECIMAL(15, 5),
    wind_speed_avg DECIMAL(15, 5),
    wind_speed_min DECIMAL(15, 5),
    wind_speed_max DECIMAL(15, 5),
    sky_condition INTEGER,
    one_hour_precipitation_avg DECIMAL(15, 5),
    one_hour_precipitation_min DECIMAL(15, 5),
    one_hour_precipitation_max DECIMAL(15, 5),
    six_hour_precipitation_avg DECIMAL(15, 5),
    six_hour_precipitation_min DECIMAL(15, 5),
    six_hour_precipitation_max DECIMAL(15, 5),
    PRIMARY KEY (station_id, date)
);
